### ISSUE TITLE
Automate release handling

### ISSUE THREAD

**Issue by skitt** [submariner-io/releases#136]
All the tedious and error-prone portions of releases are now automated, but there’s still a lot of waiting around and clicking on buttons involving humans. It would be useful to replace all that with bots, so the only requirement would be to start the process... The bot should also be able to automatically wait for image builds to complete before starting phases.

This should involve locking merges, which would involve some more automation to prevent non-release-related merges while a release is in progress.

**Comment by mkolesnik** [comment]
This intrinsically depends on #123 

I don't think this all can happen in 0.10, maybe #123 but as for entire process automation I think we have higher priority work right now

**Comment by mkolesnik** [comment]
BTW would there even be PRs on this proposal?

There are 2 types of PRs:
1. The PRs driving the process
2. The PRs the process sends to pin to specific versions

For the 1st type we could have the tooling push the commits directly without a PR which would immediately fire the release stage.

I do see a value at least for the E2E though, which checks everything works in unison.

If we're not planning to have the 2nd type, which is the more tedious and redundant type, we can alter the release process to just push directly to the repos (given that branch protections wont make this impossible).

**Comment by nyechiel** [comment]
@skitt @mkolesnik can we close this one or do we want to track any particular improvement?

**Comment by dfarrell07** [comment]
Talking about this on the PR scrub today, it seems like this is too broad to be useful. We should raise more detailed issues with things we want to automate.

Ideas:
* Block steps on waiting for post-merge jobs to finish.
* Don't require two reviews? (this is very tentative, might not be desirable)
* Reliability of pinning.
* Make sure the SHAs in the release YAMLs are the latest.
* Make it impossible to skip over pending pinning PRs.

**Comment by mkolesnik** [comment]
> Talking about this on the PR scrub today, it seems like this is too broad to be useful. We should raise more detailed issues with things we want to automate.
> 
> Ideas:
> 
>     * Block steps on waiting for post-merge jobs to finish.

This should already be happening with the E2E since it'll fail to pull the images if they haven't been successfully built and published. If not, we can open an issue.

> 
>     * Don't require two reviews? (this is very tentative, might not be desirable)

If we desire this (which I don't think), we need to address this on the team level.

Another option (from the process perspective itself) is assigning one of the maintainers as a "release supervisor" that will follow the release for the day to provide "code owner" reviews, since the 2nd +1 can be anyone and usually we're stuck waiting on the code owner review.

Also it would be nice if we had a bot send messages for new PRs on releases to the slack channel, but unfortunately it seems K8s slack is quite restrictive of the automations it allows.

> 
>     * Reliability of pinning.

Opened #303 

> 
>     * Make sure the SHAs in the release YAMLs are the latest.

Opened #302 

> 
>     * Make it impossible to skip over pending pinning PRs.

Opened #301
