### ISSUE TITLE
Propogate changes from release-* to devel

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/releases#138]
Pinning the dependency versions on `release-*` branch does not change the versions on `devel`.

For eg.

In submariner-operator

On devel, shipyard version is v0.9.0-rc0 
https://github.com/submariner-io/submariner-operator/blob/devel/go.mod#L21

But it should be v0.9.0. Same as in release-0.9 branch
https://github.com/submariner-io/submariner-operator/blob/release-0.9/go.mod#L21

**Comment by mkolesnik** [comment]
Why is this a bug?

Devel versions should point to whatever is latest and needed, there's no *need* to back-propogate the pinning since that is done for release purposes on the respective stable branch.

**Comment by skitt** [comment]
I reckon it qualifies as a bug because it can happen that following a release, the devel branches have older dependencies than the latest release. However it could be said that this was only _noticeable_ for this release because rc0 happened on the devel branch and not the 0.9 branch (for understandable reasons).

Actually, there is arguably a larger issue, which is that in many cases the release is the first time we test a particular combination of dependencies between Submariner projects...

**Comment by mkolesnik** [comment]
OK then let dependabot update projects constantly then, it is not related to release process itself.

I this is indeed a bug then it should be on the individual projects level

**Comment by mangelajo** [comment]
It's ok that it's the first time being tested, since it will be tested by E2E, and the stable branch has testing.

We could simply send a patch to all devel branches updating the dependencies at the time of release. And anyway it should not be of great importance because devel will just catch up as soon as it needs.

we are splitting hairs IMHO :)
