### ISSUE TITLE
The release process should update the Submariner addon

### ISSUE THREAD

**Issue by skitt** [submariner-io/releases#304]
Whenever we release a new version, the release process should open a PR in https://github.com/stolostron/submariner-addon to update the appropriate branch to use the new release. This should update at least the version of the operator in use; version-bumping the Submariner dependencies would also be useful but shouldn’t be as urgent.

**Comment by nyechiel** [comment]
@mkolesnik How complex do you think such a change would be? Do you think you can do it for 0.12? 

For context, we were hurt by this in our latest 0.11.1 release (https://github.com/stolostron/submariner-addon/pull/262), and I expect it to be a challenge with each release going forward.

Other option is to mention it as a manual step in the release process docs, but automating is always preferred.

**Comment by tpantelis** [comment]
Do we think it's OK for the upstream release process to interact with a vendor-specific downstream project?

**Comment by nyechiel** [comment]
> Do we think it's OK for the upstream release process to interact with a vendor-specific downstream project?

Good point that worth a discussion. Once we move the add-on to the `open-cluster-management-io` org this should be less of a concern, but that's not the case today.

**Comment by mkolesnik** [comment]
> Do we think it's OK for the upstream release process to interact with a vendor-specific downstream project?

Well how similar is it to the bundles work that's going on (#76)?
The community-operators is also an external dependency which we're introducing, so if that's OK then I guess this is OK too.

I feel that these external dependencies should be "post step(s)" that happen after the release process is done, so that if anything fails on these steps it doesn't break our release.
It could be either the same job, or an entirely different one to make it easier to spot any problems.

> @mkolesnik How complex do you think such a change would be? Do you think you can do it for 0.12?

As for how complicated it is, it's hard to tell without actually writing the code and getting it to run. A lot of these things that seem like they should be trivial, often hit unexpected problems and become non-trivial to solve.

> Other option is to mention it as a manual step in the release process docs, but automating is always preferred.

That's always an option we can do quite quickly regardless.

**Comment by skitt** [comment]
> > Do we think it's OK for the upstream release process to interact with a vendor-specific downstream project?
> 
> Well how similar is it to the bundles work that's going on (#76)? The community-operators is also an external dependency which we're introducing, so if that's OK then I guess this is OK too.
> 
> I feel that these external dependencies should be "post step(s)" that happen after the release process is done, so that if anything fails on these steps it doesn't break our release. It could be either the same job, or an entirely different one to make it easier to spot any problems.

For the addon it might make more sense to automate the dependency bump in the addon project, not as part of the release process in Submariner. The addon automation would be better placed to know which releases to track in which branches.

**Comment by skitt** [comment]
Moved to https://github.com/stolostron/submariner-addon/issues/267
