### ISSUE TITLE
Automate release notes creation

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#454]
Once the process for documenting release notes will be decided in https://github.com/submariner-io/submariner-website/pull/802 it would be best if gathering them is automated.
The release script can gather all notes added since the last GA release, and publish them on the release objects it creates, and on the website.

We should publish to the website only on GA releases (ie not on any pre release), but on the releases we could publish each time.
For simplicity, we can only publish on GA and ignore pre-releases entirely.

Specifically:
* For releases on same stable branch, e.g. 0.13.0 -> 0.13.1, only release notes added after 0.13.0 should be gathered.
* For releases on different stable brances, e.g. 0.14.0, the release note should be gathered since branch creation, minus any release notes from last stable branch.This identification can be done by filename for simplicity, as contents could change when backporting to a stable branch.
* For pre-releases on `devel` the same logic applies (remove any release notes from last stable branch).

**Comment by skitt** [comment]
Dealing with release notes on multiple branches creates a bit of a conundrum, and I think this approach makes sense overall, as long as we find a way to indicate what the reference point is. For example, if 0.13.1 is the latest release when 0.14.0, we should mention that the changes in the 0.14.0 release notes describe changes since 0.13.1. That way there won’t be any confusion (hmm) if 0.13.2 is released.

Alternatively, we could rely on chronological order (that’s what GitHub uses to present releases anyway), but I think it’s better to be explicit.

**Comment by mkolesnik** [comment]
Yes, being explicit about it definitely sounds like a good idea.
We can add this as eg `(Since v0.13.1)`.

**Comment by tpantelis** [comment]
We ended up using release note branches on the **submariner-wensite** repo so this is no longer relevant.
